# Generated by Django 5.0.6 on 2024-05-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='person_id',
        ),
    ]
